# Generated by Django 3.1.2 on 2020-12-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue_less', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='next_move',
            new_name='player_order',
        ),
        migrations.AddField(
            model_name='session',
            name='next_player',
            field=models.IntegerField(default=0),
        ),
    ]
