# Generated by Django 3.1.2 on 2020-12-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue_less', '0002_auto_20201215_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='player_order',
            field=models.JSONField(null=True),
        ),
    ]
